# Generated by Django 4.2.11 on 2024-06-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_user_productbuy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbuy',
            old_name='User',
            new_name='user',
        ),
    ]
