# Generated by Django 4.2.11 on 2024-06-10 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='planfeaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featers', models.CharField(max_length=260)),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.plan')),
            ],
        ),
        migrations.CreateModel(
            name='bookingplans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=3)),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.plan')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
