# Generated by Django 4.2.11 on 2024-06-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planfeaters',
            old_name='Plan',
            new_name='plan',
        ),
    ]
