# Generated by Django 4.2.11 on 2024-06-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_rename_plan_planfeaters_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingplans',
            old_name='User',
            new_name='user',
        ),
    ]
