# Generated by Django 4.2.11 on 2024-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='authuser/images/default.jpg', upload_to='authuser/images/'),
        ),
    ]
